### ISSUE TITLE
GUI ready for competition

### ISSUE THREAD

**Issue by mbardwell** [albertaloop/T_SWE_2019_2020#62]
# Summary
The GUI should be ready to display telemetry data collected over UDP. We have a working GUI, but it has not been opened in over a year.

# Acceptance Criteria
* [ ] GUI opens on team laptop
* [ ] GUI tested locally. Use a bash or python program to simulate a server sending UDP data to your client (the GUI)
    * server option 1: use [`netcat`](https://help.ubidots.com/en/articles/937233-sending-tcp-udp-packets-using-netcat)
    * server option 2: write a [python script](https://pythontic.com/modules/socket/udp-client-server-example)
* [ ] Ping person assigned to https://github.com/albertaloop/T_SWE_2019_2020/issues/63 so they can get started

**Comment by Iyury1** [comment]
GUI not yet integrated with telemetry and command modules
